name: CI Build
on:
  pull_request:
  # By default, the pull_request event type is not triggered when a PR is merged into main
  push:
    branches:
      - main
      - develop

jobs:
  lint-and-unit-test:
    name: Lint & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
      - name: Run linting
        run: yarn lint
      - name: Run unit tests
        run: yarn test
      - name: Upload unit test coverage
        if: success()
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  cypress-tests:
    name: Cypress Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --immutable
      - name: Run e2e tests
        run: yarn e2e
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: OperationsGateway Screenshots
          path: cypress/screenshots
  playwright-tests-mocked:
    name: Playwright Tests (mocked)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Run playwright tests
        run: yarn playwright:test:mocked

      - name: Upload test report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: always()
        with:
          name: playwright-report-mocked-tests
          path: playwright-report/
          retention-days: 10
  playwright-tests-real:
    name: E2E Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Checkout OperationsGateway API
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: ral-facilities/operationsgateway-api
          ref: main
          path: operationsgateway-api

      # Install system dependencies
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake uuid-dev libsasl2-dev libldap2-dev libssl-dev

      # Setup Python and environment dependencies (via cache)
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'
      - name: Load Pip cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.11-${{ env.pythonLocation }}-${{ hashFiles('operationsgateway-api/.github/ci_requirements.txt') }}
      - name: Install Poetry
        run: pip install -r .github/ci_requirements.txt
        working-directory: ./operationsgateway-api

      # Install and start MongoDB
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94 # 1.12.1
        with:
          mongodb-version: '7.0'

        # Used to install mongoimport when Ubuntu 22.04 is used, identified at https://github.com/actions/runner-images/issues/6626#issuecomment-1327744126
      - name: Install MongoDB Database Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-database-tools

        # Configure correct paths in config files
      - name: Configure private key path
        run: yq -i ".auth.private_key_path = \"$GITHUB_WORKSPACE/id_rsa\"" .github/ci_config.yml
        working-directory: ./operationsgateway-api
      - name: Configure public key path
        run: yq -i ".auth.public_key_path = \"$GITHUB_WORKSPACE/id_rsa.pub\"" .github/ci_config.yml
        working-directory: ./operationsgateway-api
      - name: Configure api host
        run: yq -i ".app.host = \"0.0.0.0\"" .github/ci_config.yml
        working-directory: ./operationsgateway-api
      - name: Configure log config path
        run: yq -i ".api.log_config_path = \"$GITHUB_WORKSPACE/operationsgateway-api/operationsgateway_api/logging.ini\"" .github/ci_ingest_echo_config.yml
        working-directory: ./operationsgateway-api

      # Read the database name from the config file and store it in an environment variable
      - name: Get database name from ci_config.yml
        run: echo "DATABASE_NAME=$(grep database_name .github/ci_config.yml | cut -d ':' -f 2 | tr -d '[:space:]')" >> $GITHUB_ENV
        working-directory: ./operationsgateway-api

      # Load Poetry virtual environment dependencies and install API dependencies
      - name: Load Poetry cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-3.11-${{ hashFiles('operationsgateway-api/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --without simulated-data
        working-directory: ./operationsgateway-api

      # Setup minio and create bucket
      - name: Setup minio
        run: |
          docker run -d -p 9000:9000 --name minio \
                     -e "MINIO_ACCESS_KEY=minioadmin" \
                     -e "MINIO_SECRET_KEY=minioadmin" \
                     -v /tmp/data:/data \
                     -v /tmp/config:/root/.minio \
                     minio/minio server /data
          export AWS_ACCESS_KEY_ID=minioadmin
          export AWS_SECRET_ACCESS_KEY=minioadmin
          export AWS_EC2_METADATA_DISABLED=true
          aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://og-actions-test

      - name: Move CI config.yml to correct place
        run: cp .github/ci_config.yml operationsgateway_api/config.yml
        working-directory: ./operationsgateway-api
      - name: Setup logging configuration
        run: cp operationsgateway_api/logging.ini.example operationsgateway_api/logging.ini
        working-directory: ./operationsgateway-api
      - name: Create log file
        run: touch "./logs.log"
        working-directory: ./operationsgateway-api

      - name: Create SSH private key file for auth
        run: 'echo "$SSH_KEY_PRIVATE" > $GITHUB_WORKSPACE/id_rsa'
        shell: bash
        env:
          SSH_KEY_PRIVATE: ${{secrets.SSH_PRIVATE_KEY_FOR_AUTH_OPENSSH}}

      - name: Set permissions on private key file
        run: chmod 600 $GITHUB_WORKSPACE/id_rsa

      - name: Create SSH public key file for auth
        run: 'echo "$SSH_KEY_PUBLIC" > $GITHUB_WORKSPACE/id_rsa.pub'
        shell: bash
        env:
          SSH_KEY_PUBLIC: ${{secrets.SSH_PUBLIC_KEY_FOR_AUTH_OPENSSH}}

      # Setup steps for Echo ingestion script
      - name: Configure echo access key
        run: yq -i ".echo.access_key = \"$ECHO_S3_ACCESS_KEY\"" .github/ci_ingest_echo_config.yml
        env:
          ECHO_S3_ACCESS_KEY: ${{secrets.ECHO_S3_ACCESS_KEY}}
        working-directory: ./operationsgateway-api
      - name: Configure echo secret key
        run: yq -i ".echo.secret_key = \"$ECHO_S3_SECRET_KEY\"" .github/ci_ingest_echo_config.yml
        env:
          ECHO_S3_SECRET_KEY: ${{secrets.ECHO_S3_SECRET_KEY}}
        working-directory: ./operationsgateway-api
      - name: Copy config for Echo Ingest script to correct place
        run: cp .github/ci_ingest_echo_config.yml util/realistic_data/config.yml
        working-directory: ./operationsgateway-api

      - name: Run Echo Ingest script
        run: poetry run python util/realistic_data/ingest_echo_data.py
        working-directory: ./operationsgateway-api

      - name: Start API
        run: nohup poetry run python -m operationsgateway_api.src.main > api-output.txt &
        working-directory: ./operationsgateway-api

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --immutable

      - name: Run playwright tests
        run: yarn playwright:test:real

      - name: Upload test report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ always() }}
        with:
          name: playwright-report-real-tests
          path: playwright-report/
          retention-days: 10

      - name: Upload API logs if job fails
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ failure() }}
        with:
          name: api-logs
          path: operationsgateway-api/api-output.txt
          retention-days: 10
